-- Generated by scripts/seed.ts — do not edit by hand.
-- Regenerate with: npm run seed:sql
--
-- Every statement is an upsert on a natural key, so this file is safe to
-- run repeatedly against the same database.

-- --- brands ---------------------------------------------------------------
insert into public.brands (name, slug) values
  ('Nike', 'nike'),
  ('adidas', 'adidas'),
  ('Puma', 'puma'),
  ('New Balance', 'new-balance'),
  ('ASICS', 'asics'),
  ('Skechers', 'skechers'),
  ('Campus', 'campus'),
  ('Woodland', 'woodland'),
  ('Bata', 'bata'),
  ('Crocs', 'crocs'),
  ('Red Chief', 'red-chief'),
  ('Metro', 'metro')
on conflict (slug) do update set name = excluded.name;

-- --- categories -----------------------------------------------------------
-- Parents first: a child's parent_id is resolved by slug, so the row it
-- points at has to exist by the time the child is inserted.
insert into public.categories (name, slug, description, sort_order, image_url) values
  ('Men', 'men', 'Sneakers, formal shoes, boots and sandals for men.', 1, '/seed/category-men.svg'),
  ('Women', 'women', 'Sneakers, flats, sandals and sports shoes for women.', 2, '/seed/category-women.svg'),
  ('Kids', 'kids', 'School shoes, sneakers and sandals built for growing feet.', 3, '/seed/category-kids.svg')
on conflict (slug) do update set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order, image_url = excluded.image_url;

insert into public.categories (name, slug, description, sort_order, parent_id) values
  ('Sneakers', 'mens-sneakers', NULL, 1, (select id from public.categories where slug = 'men')),
  ('Formal', 'mens-formal', NULL, 2, (select id from public.categories where slug = 'men')),
  ('Sports', 'mens-sports', NULL, 3, (select id from public.categories where slug = 'men')),
  ('Sandals & Slides', 'mens-sandals', NULL, 4, (select id from public.categories where slug = 'men')),
  ('Boots', 'mens-boots', NULL, 5, (select id from public.categories where slug = 'men')),
  ('Sneakers', 'womens-sneakers', NULL, 1, (select id from public.categories where slug = 'women')),
  ('Flats & Loafers', 'womens-flats', NULL, 2, (select id from public.categories where slug = 'women')),
  ('Sports', 'womens-sports', NULL, 3, (select id from public.categories where slug = 'women')),
  ('Sandals & Slides', 'womens-sandals', NULL, 4, (select id from public.categories where slug = 'women')),
  ('School Shoes', 'kids-school', NULL, 1, (select id from public.categories where slug = 'kids')),
  ('Sneakers', 'kids-sneakers', NULL, 2, (select id from public.categories where slug = 'kids')),
  ('Sandals', 'kids-sandals', NULL, 3, (select id from public.categories where slug = 'kids'))
on conflict (slug) do update set name = excluded.name, sort_order = excluded.sort_order, parent_id = excluded.parent_id;

-- --- products -------------------------------------------------------------
insert into public.products (name, slug, description, category_id, brand_id, gender, footwear_type, material, base_price, sale_price, is_featured, meta_title, meta_description, search_keywords) values
  ('Air Max 90', 'nike-air-max-90-mens', 'The 1990 silhouette, unchanged where it matters. Visible Air in the heel, waffle outsole, and the stitched overlays that let it take a monsoon without falling apart.', (select id from public.categories where slug = 'mens-sneakers'), (select id from public.brands where slug = 'nike'), 'men', 'sneaker', 'Leather and mesh upper, rubber outsole', 1299500, 974600, true, 'Air Max 90 — Nike', 'The 1990 silhouette, unchanged where it matters.', array['casual', 'trainers', 'lifestyle', 'everyday', 'street']::text[]),
  ('Samba OG', 'adidas-samba-og-mens', 'An indoor football shoe from 1950 that never needed redesigning. Low profile, gum sole, suede T-toe. Runs about half a size small — take the next size up if you are between.', (select id from public.categories where slug = 'mens-sneakers'), (select id from public.brands where slug = 'adidas'), 'unisex', 'sneaker', 'Full-grain leather upper, gum rubber outsole', 999900, NULL, true, 'Samba OG — adidas', 'An indoor football shoe from 1950 that never needed redesigning.', array['casual', 'trainers', 'lifestyle', 'everyday', 'street']::text[]),
  ('550', 'new-balance-550-mens', 'A 1989 basketball shoe brought back with the proportions intact. Stiff leather that creases in properly after a fortnight, and a cupsole that takes daily wear.', (select id from public.categories where slug = 'mens-sneakers'), (select id from public.brands where slug = 'new-balance'), 'unisex', 'sneaker', 'Leather upper, rubber cupsole', 1149900, NULL, true, '550 — New Balance', 'A 1989 basketball shoe brought back with the proportions intact.', array['casual', 'trainers', 'lifestyle', 'everyday', 'street']::text[]),
  ('Suede Classic XXI', 'puma-suede-classic-mens', 'Fifty years of the same shoe. Soft suede, formstrip, flat rubber sole. Brush it after the rain and it looks new.', (select id from public.categories where slug = 'mens-sneakers'), (select id from public.brands where slug = 'puma'), 'unisex', 'sneaker', 'Suede upper, rubber outsole', 649900, 454900, false, 'Suede Classic XXI — Puma', 'Fifty years of the same shoe.', array['casual', 'trainers', 'lifestyle', 'everyday', 'street']::text[]),
  ('North Plus', 'campus-north-plus-mens', 'The everyday trainer that does not pretend to be anything else. Light mesh, cushioned collar, and a price that survives being worn out in a year.', (select id from public.categories where slug = 'mens-sneakers'), (select id from public.brands where slug = 'campus'), 'men', 'sneaker', 'Mesh upper, EVA midsole, TPR outsole', 199900, 139900, false, 'North Plus — Campus', 'The everyday trainer that does not pretend to be anything else.', array['casual', 'trainers', 'lifestyle', 'everyday', 'street']::text[]),
  ('Go Walk 7', 'skechers-go-walk-7-mens', 'Slip-on, machine washable, and light enough that you forget you are wearing them. The one people buy a second pair of.', (select id from public.categories where slug = 'mens-sneakers'), (select id from public.brands where slug = 'skechers'), 'men', 'sneaker', 'Engineered knit upper, Air-Cooled Goga Mat insole', 699900, NULL, false, 'Go Walk 7 — Skechers', 'Slip-on, machine washable, and light enough that you forget you are wearing them.', array['casual', 'trainers', 'lifestyle', 'everyday', 'street']::text[]),
  ('Gel-Nimbus 27', 'asics-gel-nimbus-27-mens', 'A max-cushion daily trainer for long, slow kilometres. Broad base, soft heel, and enough foam to take the sting out of concrete.', (select id from public.categories where slug = 'mens-sports'), (select id from public.brands where slug = 'asics'), 'men', 'sports', 'Engineered knit upper, FF Blast Plus Eco midsole', 1699900, NULL, true, 'Gel-Nimbus 27 — ASICS', 'A max-cushion daily trainer for long, slow kilometres.', array['running', 'runner', 'trainer', 'training', 'gym', 'jogging', 'workout', 'marathon']::text[]),
  ('Pegasus 41', 'nike-pegasus-41-mens', 'The workhorse. Two Air Zoom units under forefoot and heel, responsive enough for tempo work and forgiving enough for the easy days between.', (select id from public.categories where slug = 'mens-sports'), (select id from public.brands where slug = 'nike'), 'men', 'sports', 'Mesh upper, ReactX foam midsole, Air Zoom units', 1189500, 951600, false, 'Pegasus 41 — Nike', 'The workhorse.', array['running', 'runner', 'trainer', 'training', 'gym', 'jogging', 'workout', 'marathon']::text[]),
  ('Adizero SL', 'adidas-adizero-sl-mens', 'Light, snappy, and cheap enough to actually race in. The training shoe from the Adizero line without the carbon plate or the price.', (select id from public.categories where slug = 'mens-sports'), (select id from public.brands where slug = 'adidas'), 'unisex', 'sports', 'Lightweight mesh upper, Lightstrike Pro midsole', 999900, NULL, false, 'Adizero SL — adidas', 'Light, snappy, and cheap enough to actually race in.', array['running', 'runner', 'trainer', 'training', 'gym', 'jogging', 'workout', 'marathon']::text[]),
  ('Velocity Nitro 3', 'puma-velocity-nitro-3-mens', 'Nitrogen-injected foam and a genuinely good rubber outsole. Grips a wet road, which most trainers in this range do not.', (select id from public.categories where slug = 'mens-sports'), (select id from public.brands where slug = 'puma'), 'men', 'sports', 'Mesh upper, Nitro foam midsole, PUMAGRIP outsole', 1199900, 839900, false, 'Velocity Nitro 3 — Puma', 'Nitrogen-injected foam and a genuinely good rubber outsole.', array['running', 'runner', 'trainer', 'training', 'gym', 'jogging', 'workout', 'marathon']::text[]),
  ('Leather Oxford', 'red-chief-oxford-mens', 'A closed-lacing Oxford in full-grain leather that takes polish properly. Cushioned footbed, so it survives a full day of standing at a wedding.', (select id from public.categories where slug = 'mens-formal'), (select id from public.brands where slug = 'red-chief'), 'men', 'formal', 'Full-grain buffalo leather, leather lining, TPR sole', 429500, NULL, true, 'Leather Oxford — Red Chief', 'A closed-lacing Oxford in full-grain leather that takes polish properly.', array['office', 'dress', 'wedding', 'oxford', 'derby', 'business']::text[]),
  ('Remo Derby', 'bata-derby-mens', 'The office shoe that does not need thinking about. Open lacing, slim last, and a sole you can resole once before replacing.', (select id from public.categories where slug = 'mens-formal'), (select id from public.brands where slug = 'bata'), 'men', 'formal', 'Synthetic leather upper, PVC sole', 179900, 125900, false, 'Remo Derby — Bata', 'The office shoe that does not need thinking about.', array['office', 'dress', 'wedding', 'oxford', 'derby', 'business']::text[]),
  ('Penny Loafer', 'metro-penny-loafer-mens', 'A slip-on with a proper leather sole and a saddle strap. Wears in around the instep after a week and then fits like nothing else.', (select id from public.categories where slug = 'mens-formal'), (select id from public.brands where slug = 'metro'), 'men', 'formal', 'Genuine leather upper, leather sole', 399900, NULL, false, 'Penny Loafer — Metro', 'A slip-on with a proper leather sole and a saddle strap.', array['office', 'dress', 'wedding', 'oxford', 'derby', 'business']::text[]),
  ('Leather Brogue', 'woodland-brogue-mens', 'Broguing on a chunkier last with a real rubber outsole. A formal shoe that copes with a broken pavement.', (select id from public.categories where slug = 'mens-formal'), (select id from public.brands where slug = 'woodland'), 'men', 'formal', 'Nubuck leather, rubber outsole', 549500, 439600, false, 'Leather Brogue — Woodland', 'Broguing on a chunkier last with a real rubber outsole.', array['office', 'dress', 'wedding', 'oxford', 'derby', 'business']::text[]),
  ('Camel Leather Boot', 'woodland-camel-boot-mens', 'The boot the brand is known for. Nubuck upper, hand-stitched welt, and a sole bonded rather than glued so it does not part company in the rain.', (select id from public.categories where slug = 'mens-boots'), (select id from public.brands where slug = 'woodland'), 'men', 'boot', 'Nubuck leather upper, PU direct-injected sole', 699500, NULL, true, 'Camel Leather Boot — Woodland', 'The boot the brand is known for.', array['ankle', 'hiking', 'outdoor', 'trekking', 'winter']::text[]),
  ('Leather Chukka', 'red-chief-chukka-mens', 'Two eyelets, suede upper, crepe sole. Sits between a shoe and a boot, which makes it the one that gets worn most.', (select id from public.categories where slug = 'mens-boots'), (select id from public.brands where slug = 'red-chief'), 'men', 'boot', 'Suede leather upper, crepe rubber sole', 499500, NULL, false, 'Leather Chukka — Red Chief', 'Two eyelets, suede upper, crepe sole.', array['ankle', 'hiking', 'outdoor', 'trekking', 'winter']::text[]),
  ('Classic Clog', 'crocs-classic-clog-unisex', 'Waterproof, washable, and the only thing worth owning in a monsoon. Pivoting heel strap for a closed fit, or back for a slide.', (select id from public.categories where slug = 'mens-sandals'), (select id from public.brands where slug = 'crocs'), 'unisex', 'slide', 'Croslite foam', 399500, 279600, true, 'Classic Clog — Crocs', 'Waterproof, washable, and the only thing worth owning in a monsoon.', array['chappal', 'monsoon', 'pool', 'beach', 'slipper', 'sliders']::text[]),
  ('Adilette Comfort Slide', 'adidas-adilette-slide-unisex', 'A pool slide with a contoured foam footbed. Dries in minutes and takes being left on a wet balcony.', (select id from public.categories where slug = 'mens-sandals'), (select id from public.brands where slug = 'adidas'), 'unisex', 'slide', 'Synthetic bandage upper, Cloudfoam Plus footbed', 299900, 194900, false, 'Adilette Comfort Slide — adidas', 'A pool slide with a contoured foam footbed.', array['chappal', 'monsoon', 'pool', 'beach', 'slipper', 'sliders']::text[]),
  ('Floater Sandal', 'bata-floater-sandal-mens', 'Three adjustable straps, a grippy outsole, and a footbed that does not flatten by the second month. Built for the walk to the market and back.', (select id from public.categories where slug = 'mens-sandals'), (select id from public.brands where slug = 'bata'), 'men', 'sandal', 'Synthetic webbing upper, EVA footbed, rubber outsole', 149900, NULL, false, 'Floater Sandal — Bata', 'Three adjustable straps, a grippy outsole, and a footbed that does not flatten by the second month.', array['chappal', 'monsoon', 'summer', 'open', 'strappy']::text[]),
  ('Epic Flip', 'puma-flip-flop-unisex', 'A flip-flop with a moulded arch instead of a flat slab of foam. Costs a little more and lasts three times as long.', (select id from public.categories where slug = 'mens-sandals'), (select id from public.brands where slug = 'puma'), 'unisex', 'flipflop', 'Synthetic thong strap, EVA footbed', 99900, 69900, false, 'Epic Flip — Puma', 'A flip-flop with a moulded arch instead of a flat slab of foam.', array['chappal', 'thong', 'beach', 'monsoon', 'slipper']::text[]),
  ('Court Vision Low', 'nike-court-vision-womens', 'A clean court silhouette with a stitched leather upper. Goes with everything, which is the entire point of a white sneaker.', (select id from public.categories where slug = 'womens-sneakers'), (select id from public.brands where slug = 'nike'), 'women', 'sneaker', 'Leather upper, rubber cupsole', 599500, 419600, true, 'Court Vision Low — Nike', 'A clean court silhouette with a stitched leather upper.', array['casual', 'trainers', 'lifestyle', 'everyday', 'street']::text[]),
  ('Gazelle', 'adidas-gazelle-womens', 'Suede upper, slim last, gum sole. A training shoe from 1966 that has spent the last forty years being worn anywhere but the gym.', (select id from public.categories where slug = 'womens-sneakers'), (select id from public.brands where slug = 'adidas'), 'women', 'sneaker', 'Suede upper, gum rubber outsole', 899900, NULL, true, 'Gazelle — adidas', 'Suede upper, slim last, gum sole.', array['casual', 'trainers', 'lifestyle', 'everyday', 'street']::text[]),
  ('327', 'new-balance-327-womens', 'An oversized N and a flared 70s outsole. Sits lower than it looks in photographs and runs true to size.', (select id from public.categories where slug = 'womens-sneakers'), (select id from public.brands where slug = 'new-balance'), 'women', 'sneaker', 'Suede and nylon upper, EVA midsole', 999900, 699900, false, '327 — New Balance', 'An oversized N and a flared 70s outsole.', array['casual', 'trainers', 'lifestyle', 'everyday', 'street']::text[]),
  ('Summits', 'skechers-summits-womens', 'Wide-fit mesh with a memory foam insole. The pair people buy when they are on their feet for eight hours.', (select id from public.categories where slug = 'womens-sneakers'), (select id from public.brands where slug = 'skechers'), 'women', 'sneaker', 'Mesh upper, Air-Cooled Memory Foam insole', 449900, NULL, false, 'Summits — Skechers', 'Wide-fit mesh with a memory foam insole.', array['casual', 'trainers', 'lifestyle', 'everyday', 'street']::text[]),
  ('Leather Ballerina', 'metro-ballerina-womens', 'A soft leather flat with a padded insole and a sole that grips. Folds enough to live in a bag without creasing badly.', (select id from public.categories where slug = 'womens-flats'), (select id from public.brands where slug = 'metro'), 'women', 'formal', 'Genuine leather upper, cushioned insole, TPR sole', 279900, 195900, false, 'Leather Ballerina — Metro', 'A soft leather flat with a padded insole and a sole that grips.', array['office', 'dress', 'wedding', 'oxford', 'derby', 'business']::text[]),
  ('Slip-On Loafer', 'bata-loafer-womens', 'A round-toe loafer with a low block heel. Formal enough for an office, forgiving enough for a commute.', (select id from public.categories where slug = 'womens-flats'), (select id from public.brands where slug = 'bata'), 'women', 'formal', 'Synthetic leather upper, memory foam insole', 199900, NULL, false, 'Slip-On Loafer — Bata', 'A round-toe loafer with a low block heel.', array['office', 'dress', 'wedding', 'oxford', 'derby', 'business']::text[]),
  ('Gel-Cumulus 27', 'asics-gel-cumulus-27-womens', 'A neutral daily trainer that does not overreach. Softer than the Nimbus underfoot at the forefoot, and lighter by a good margin.', (select id from public.categories where slug = 'womens-sports'), (select id from public.brands where slug = 'asics'), 'women', 'sports', 'Jacquard mesh upper, FF Blast Plus midsole', 1399900, 1049900, false, 'Gel-Cumulus 27 — ASICS', 'A neutral daily trainer that does not overreach.', array['running', 'runner', 'trainer', 'training', 'gym', 'jogging', 'workout', 'marathon']::text[]),
  ('Softride Enzo', 'puma-softride-womens', 'A gym and walking shoe with a rocker sole. Slips on, holds the heel, and is quiet on a treadmill.', (select id from public.categories where slug = 'womens-sports'), (select id from public.brands where slug = 'puma'), 'women', 'sports', 'Knit upper, Softride foam midsole', 599900, 359900, false, 'Softride Enzo — Puma', 'A gym and walking shoe with a rocker sole.', array['running', 'runner', 'trainer', 'training', 'gym', 'jogging', 'workout', 'marathon']::text[]),
  ('Brooklyn Low Wedge', 'crocs-brooklyn-slide-womens', 'A low wedge that is still entirely foam — waterproof, weightless, and washable under a tap.', (select id from public.categories where slug = 'womens-sandals'), (select id from public.brands where slug = 'crocs'), 'women', 'slide', 'Croslite foam, textured footbed', 449500, 314600, false, 'Brooklyn Low Wedge — Crocs', 'A low wedge that is still entirely foam — waterproof, weightless, and washable under a tap.', array['chappal', 'monsoon', 'pool', 'beach', 'slipper', 'sliders']::text[]),
  ('Naughty Boy School Shoe', 'bata-school-shoe-kids', 'The black school shoe, with velcro instead of laces so it gets fastened properly. Scuffs wipe off with a damp cloth.', (select id from public.categories where slug = 'kids-school'), (select id from public.brands where slug = 'bata'), 'kids', 'formal', 'Synthetic leather upper, PVC sole, velcro strap', 129900, NULL, true, 'Naughty Boy School Shoe — Bata', 'The black school shoe, with velcro instead of laces so it gets fastened properly.', array['office', 'dress', 'wedding', 'oxford', 'derby', 'business']::text[]),
  ('Junior Runner', 'campus-kids-sneaker', 'Light mesh, velcro, and a sole with real grip for a playground. Cheap enough to replace when the foot outgrows it in eight months.', (select id from public.categories where slug = 'kids-sneakers'), (select id from public.brands where slug = 'campus'), 'kids', 'sneaker', 'Mesh upper, EVA midsole, velcro closure', 109900, 76900, false, 'Junior Runner — Campus', 'Light mesh, velcro, and a sole with real grip for a playground.', array['casual', 'trainers', 'lifestyle', 'everyday', 'street']::text[]),
  ('Classic Clog Kids', 'crocs-kids-clog', 'The adult clog, scaled down, with the same heel strap. Survives a puddle, a beach and a wash cycle.', (select id from public.categories where slug = 'kids-sandals'), (select id from public.brands where slug = 'crocs'), 'kids', 'slide', 'Croslite foam', 249500, NULL, false, 'Classic Clog Kids — Crocs', 'The adult clog, scaled down, with the same heel strap.', array['chappal', 'monsoon', 'pool', 'beach', 'slipper', 'sliders']::text[]),
  ('Gazelle Indoor', 'adidas-gazelle-indoor-womens', 'The indoor court shape, in suede, with the gum sole that marks nothing. This colourway sold through in a fortnight and is not coming back — the run below is the full run.', (select id from public.categories where slug = 'womens-sneakers'), (select id from public.brands where slug = 'adidas'), 'women', 'sneaker', 'Suede upper, gum rubber outsole', 1099900, NULL, false, 'Gazelle Indoor — adidas', 'The indoor court shape, in suede, with the gum sole that marks nothing.', array['casual', 'trainers', 'lifestyle', 'everyday', 'street']::text[]),
  ('Nubuck Trek Boot', 'woodland-nubuck-trek-mens', 'End of the line. One pair left, in one size, at the price it always was.', (select id from public.categories where slug = 'mens-boots'), (select id from public.brands where slug = 'woodland'), 'men', 'boot', 'Nubuck leather upper, stitched-down rubber outsole', 649500, NULL, false, 'Nubuck Trek Boot — Woodland', 'End of the line.', array['ankle', 'hiking', 'outdoor', 'trekking', 'winter']::text[]),
  ('Gel-Kayano 31 Wide Fit Stability Running Trainer for Overpronation', 'asics-gel-kayano-31-wide-womens', 'The stability trainer, in the wide fit, for a foot that rolls in. Guidance comes from the sole geometry rather than a hard post, so it does not fight a neutral stride on the days you have one.', (select id from public.categories where slug = 'womens-sports'), (select id from public.brands where slug = 'asics'), 'women', 'sports', 'Engineered knit upper, FF Blast Plus Eco midsole', 1599900, 1279900, false, 'Gel-Kayano 31 Wide Fit Stability Running Trainer for Overpronation — ASICS', 'The stability trainer, in the wide fit, for a foot that rolls in.', array['running', 'runner', 'trainer', 'training', 'gym', 'jogging', 'workout', 'marathon']::text[])
on conflict (slug) do update set name = excluded.name, description = excluded.description, category_id = excluded.category_id, brand_id = excluded.brand_id, gender = excluded.gender, footwear_type = excluded.footwear_type, material = excluded.material, base_price = excluded.base_price, sale_price = excluded.sale_price, is_featured = excluded.is_featured, meta_title = excluded.meta_title, meta_description = excluded.meta_description, search_keywords = excluded.search_keywords;

-- --- images ---------------------------------------------------------------
-- One hero and one outsole per *colourway*, not per product: the swatches on
-- the product page change the gallery, which they can only do if the gallery
-- has something to change to.
--
-- Set-based rather than one row per image: the URL and the alt text are both
-- derived from the product and the colour, so listing them as literals would
-- only be more places for them to drift out of step with
-- scripts/generate-seed-images.ts. The colour slug below is the SQL twin of
-- colorSlug() in that file — a mismatch is a broken image, so they change
-- together.
--
-- Cleared first because product_images has no natural key to upsert on, and
-- the partial unique index on (product_id) where is_primary would reject a
-- second primary before the first was gone.
delete from public.product_images;
with colorway (product_slug, color, position) as (values
  ('nike-air-max-90-mens', 'White / Grey', 0),
  ('nike-air-max-90-mens', 'Black / Volt', 1),
  ('adidas-samba-og-mens', 'Core Black', 0),
  ('adidas-samba-og-mens', 'Cloud White', 1),
  ('new-balance-550-mens', 'White / Green', 0),
  ('new-balance-550-mens', 'White / Navy', 1),
  ('puma-suede-classic-mens', 'Peacoat Navy', 0),
  ('puma-suede-classic-mens', 'Team Red', 1),
  ('campus-north-plus-mens', 'Grey', 0),
  ('campus-north-plus-mens', 'Black', 1),
  ('campus-north-plus-mens', 'Navy', 2),
  ('skechers-go-walk-7-mens', 'Charcoal', 0),
  ('skechers-go-walk-7-mens', 'Taupe', 1),
  ('asics-gel-nimbus-27-mens', 'Black / Gold', 0),
  ('asics-gel-nimbus-27-mens', 'Sky Blue', 1),
  ('nike-pegasus-41-mens', 'Black / White', 0),
  ('nike-pegasus-41-mens', 'Wolf Grey', 1),
  ('adidas-adizero-sl-mens', 'Core Black', 0),
  ('puma-velocity-nitro-3-mens', 'Fire Orchid', 0),
  ('puma-velocity-nitro-3-mens', 'Black', 1),
  ('red-chief-oxford-mens', 'Tan', 0),
  ('red-chief-oxford-mens', 'Black', 1),
  ('bata-derby-mens', 'Black', 0),
  ('metro-penny-loafer-mens', 'Coffee Brown', 0),
  ('metro-penny-loafer-mens', 'Black', 1),
  ('woodland-brogue-mens', 'Khaki', 0),
  ('woodland-camel-boot-mens', 'Camel', 0),
  ('woodland-camel-boot-mens', 'Olive', 1),
  ('red-chief-chukka-mens', 'Rust', 0),
  ('crocs-classic-clog-unisex', 'Navy', 0),
  ('crocs-classic-clog-unisex', 'Black', 1),
  ('crocs-classic-clog-unisex', 'Bone', 2),
  ('adidas-adilette-slide-unisex', 'Black', 0),
  ('adidas-adilette-slide-unisex', 'Navy', 1),
  ('bata-floater-sandal-mens', 'Brown', 0),
  ('bata-floater-sandal-mens', 'Black', 1),
  ('puma-flip-flop-unisex', 'Black / White', 0),
  ('nike-court-vision-womens', 'White / Pink', 0),
  ('nike-court-vision-womens', 'White / Black', 1),
  ('adidas-gazelle-womens', 'Collegiate Green', 0),
  ('adidas-gazelle-womens', 'Wonder Beige', 1),
  ('new-balance-327-womens', 'Sea Salt', 0),
  ('skechers-summits-womens', 'Grey / Lavender', 0),
  ('skechers-summits-womens', 'All Black', 1),
  ('metro-ballerina-womens', 'Black', 0),
  ('metro-ballerina-womens', 'Tan', 1),
  ('bata-loafer-womens', 'Black', 0),
  ('asics-gel-cumulus-27-womens', 'Digital Aqua', 0),
  ('puma-softride-womens', 'Rose', 0),
  ('puma-softride-womens', 'Black', 1),
  ('crocs-brooklyn-slide-womens', 'Bone', 0),
  ('crocs-brooklyn-slide-womens', 'Black', 1),
  ('bata-school-shoe-kids', 'Black', 0),
  ('campus-kids-sneaker', 'Blue', 0),
  ('campus-kids-sneaker', 'Pink', 1),
  ('crocs-kids-clog', 'Bright Blue', 0),
  ('crocs-kids-clog', 'Bubblegum', 1),
  ('adidas-gazelle-indoor-womens', 'Collegiate Green', 0),
  ('woodland-nubuck-trek-mens', 'Khaki', 0),
  ('asics-gel-kayano-31-wide-womens', 'Sea Salt', 0),
  ('asics-gel-kayano-31-wide-womens', 'Peacoat Navy', 1)
),
view (kind, offset_in_pair, suffix) as (values
  ('hero', 0, ', side profile'),
  ('sole', 1, ' outsole')
)
insert into public.product_images (product_id, url, alt_text, sort_order, is_primary, color)
select p.id,
       '/seed/' || p.slug || '-'
         || trim(both '-' from lower(regexp_replace(c.color, '[^a-zA-Z0-9]+', '-', 'g')))
         || '-' || v.kind || '.svg',
       p.name || ' in ' || c.color || v.suffix,
       c.position * 2 + v.offset_in_pair,
       -- Exactly one primary per product: the first colourway's hero. It is
       -- what the card shows and what the gallery opens on.
       c.position = 0 and v.kind = 'hero',
       c.color
  from public.products p
  join colorway c on c.product_slug = p.slug
  cross join view v;

-- --- variants -------------------------------------------------------------
-- One row per size per colourway, generated by joining each product to the
-- size run for its gender. 384 variants, without 384 lines of literals for a
-- reviewer to check the SKU format on.
--
-- Stock is 8 unless the override table below says otherwise: 0 for a size
-- that is genuinely out, or the real remaining count for a size down to its
-- last pairs.
with run (gender, sizes) as (values
  ('men'::public.gender_group,    array['6', '7', '8', '9', '10', '11', '12']),
  ('unisex'::public.gender_group, array['6', '7', '8', '9', '10', '11', '12']),
  ('women'::public.gender_group,  array['3', '4', '5', '6', '7', '8']),
  ('kids'::public.gender_group,   array['10C', '11C', '12C', '13C', '1', '2', '3'])
),
colorway (product_slug, color, hex) as (values
  ('nike-air-max-90-mens', 'White / Grey', '#e8e8e8'),
  ('nike-air-max-90-mens', 'Black / Volt', '#1a1a1a'),
  ('adidas-samba-og-mens', 'Core Black', '#141414'),
  ('adidas-samba-og-mens', 'Cloud White', '#f4f1ec'),
  ('new-balance-550-mens', 'White / Green', '#f2f2ee'),
  ('new-balance-550-mens', 'White / Navy', '#eceff5'),
  ('puma-suede-classic-mens', 'Peacoat Navy', '#232c3d'),
  ('puma-suede-classic-mens', 'Team Red', '#7d1f27'),
  ('campus-north-plus-mens', 'Grey', '#8b8d92'),
  ('campus-north-plus-mens', 'Black', '#191919'),
  ('campus-north-plus-mens', 'Navy', '#22304a'),
  ('skechers-go-walk-7-mens', 'Charcoal', '#3d4046'),
  ('skechers-go-walk-7-mens', 'Taupe', '#9a8d7d'),
  ('asics-gel-nimbus-27-mens', 'Black / Gold', '#17181c'),
  ('asics-gel-nimbus-27-mens', 'Sky Blue', '#8fb6d6'),
  ('nike-pegasus-41-mens', 'Black / White', '#141519'),
  ('nike-pegasus-41-mens', 'Wolf Grey', '#9aa0a8'),
  ('adidas-adizero-sl-mens', 'Core Black', '#151515'),
  ('puma-velocity-nitro-3-mens', 'Fire Orchid', '#c33a2f'),
  ('puma-velocity-nitro-3-mens', 'Black', '#181818'),
  ('red-chief-oxford-mens', 'Tan', '#8a5a2b'),
  ('red-chief-oxford-mens', 'Black', '#151515'),
  ('bata-derby-mens', 'Black', '#131313'),
  ('metro-penny-loafer-mens', 'Coffee Brown', '#4a3223'),
  ('metro-penny-loafer-mens', 'Black', '#161616'),
  ('woodland-brogue-mens', 'Khaki', '#6f6244'),
  ('woodland-camel-boot-mens', 'Camel', '#a97a48'),
  ('woodland-camel-boot-mens', 'Olive', '#4d5334'),
  ('red-chief-chukka-mens', 'Rust', '#8c4a2f'),
  ('crocs-classic-clog-unisex', 'Navy', '#1f3a5f'),
  ('crocs-classic-clog-unisex', 'Black', '#1a1a1a'),
  ('crocs-classic-clog-unisex', 'Bone', '#ded4c5'),
  ('adidas-adilette-slide-unisex', 'Black', '#171717'),
  ('adidas-adilette-slide-unisex', 'Navy', '#22334f'),
  ('bata-floater-sandal-mens', 'Brown', '#5b4230'),
  ('bata-floater-sandal-mens', 'Black', '#181818'),
  ('puma-flip-flop-unisex', 'Black / White', '#1c1c1c'),
  ('nike-court-vision-womens', 'White / Pink', '#f6f3f0'),
  ('nike-court-vision-womens', 'White / Black', '#f2f2f2'),
  ('adidas-gazelle-womens', 'Collegiate Green', '#2f5340'),
  ('adidas-gazelle-womens', 'Wonder Beige', '#d8c8b4'),
  ('new-balance-327-womens', 'Sea Salt', '#e5ddd0'),
  ('skechers-summits-womens', 'Grey / Lavender', '#a09fae'),
  ('skechers-summits-womens', 'All Black', '#1b1b1b'),
  ('metro-ballerina-womens', 'Black', '#171717'),
  ('metro-ballerina-womens', 'Tan', '#a97852'),
  ('bata-loafer-womens', 'Black', '#151515'),
  ('asics-gel-cumulus-27-womens', 'Digital Aqua', '#7fc0c4'),
  ('puma-softride-womens', 'Rose', '#c88a8e'),
  ('puma-softride-womens', 'Black', '#1a1a1a'),
  ('crocs-brooklyn-slide-womens', 'Bone', '#dfd6c8'),
  ('crocs-brooklyn-slide-womens', 'Black', '#1c1c1c'),
  ('bata-school-shoe-kids', 'Black', '#141414'),
  ('campus-kids-sneaker', 'Blue', '#2f5aa8'),
  ('campus-kids-sneaker', 'Pink', '#d4718f'),
  ('crocs-kids-clog', 'Bright Blue', '#2a7fd4'),
  ('crocs-kids-clog', 'Bubblegum', '#e08aa8'),
  ('adidas-gazelle-indoor-womens', 'Collegiate Green', '#2f5340'),
  ('woodland-nubuck-trek-mens', 'Khaki', '#6f6244'),
  ('asics-gel-kayano-31-wide-womens', 'Sea Salt', '#e5ddd0'),
  ('asics-gel-kayano-31-wide-womens', 'Peacoat Navy', '#232c3d')
),
override (product_slug, size, qty) as (values
  ('nike-air-max-90-mens', '6', 0),
  ('nike-air-max-90-mens', '9', 2),
  ('nike-air-max-90-mens', '10', 3),
  ('nike-air-max-90-mens', '12', 0),
  ('adidas-samba-og-mens', '6', 0),
  ('adidas-samba-og-mens', '8', 1),
  ('new-balance-550-mens', '11', 2),
  ('puma-suede-classic-mens', '12', 0),
  ('campus-north-plus-mens', '7', 3),
  ('skechers-go-walk-7-mens', '6', 0),
  ('skechers-go-walk-7-mens', '7', 0),
  ('asics-gel-nimbus-27-mens', '9', 2),
  ('asics-gel-nimbus-27-mens', '11', 1),
  ('nike-pegasus-41-mens', '12', 0),
  ('adidas-adizero-sl-mens', '10', 2),
  ('red-chief-oxford-mens', '8', 2),
  ('bata-derby-mens', '11', 0),
  ('bata-derby-mens', '12', 0),
  ('metro-penny-loafer-mens', '9', 1),
  ('woodland-camel-boot-mens', '6', 0),
  ('woodland-camel-boot-mens', '10', 2),
  ('crocs-classic-clog-unisex', '9', 3),
  ('adidas-adilette-slide-unisex', '12', 0),
  ('nike-court-vision-womens', '5', 2),
  ('adidas-gazelle-womens', '3', 0),
  ('new-balance-327-womens', '6', 1),
  ('metro-ballerina-womens', '4', 2),
  ('bata-loafer-womens', '8', 0),
  ('asics-gel-cumulus-27-womens', '5', 2),
  ('crocs-brooklyn-slide-womens', '6', 3),
  ('bata-school-shoe-kids', '13C', 2),
  ('campus-kids-sneaker', '3', 0),
  ('crocs-kids-clog', '12C', 1),
  ('adidas-gazelle-indoor-womens', '3', 0),
  ('adidas-gazelle-indoor-womens', '4', 0),
  ('adidas-gazelle-indoor-womens', '5', 0),
  ('adidas-gazelle-indoor-womens', '6', 0),
  ('adidas-gazelle-indoor-womens', '7', 0),
  ('adidas-gazelle-indoor-womens', '8', 0),
  ('woodland-nubuck-trek-mens', '9', 1),
  ('asics-gel-kayano-31-wide-womens', '7', 2),
  ('asics-gel-kayano-31-wide-womens', '8', 0)
)
insert into public.product_variants (product_id, size, color, color_hex, sku, stock_quantity)
select p.id, s.size, c.color, c.hex,
       -- FV-BRAND-MODEL-COLOUR-SIZE, matching skuFor() in seed.ts. The model
       -- segment strips the brand prefix off the slug, because two adidas
       -- products share their first six characters and would otherwise share
       -- a SKU in a shared colourway.
       'FV-' || upper(left(regexp_replace(b.slug, '[^a-zA-Z0-9]', '', 'g'), 6))
           || '-' || upper(left(regexp_replace(
                case when p.slug like b.slug || '-%'
                     then substr(p.slug, length(b.slug) + 2)
                     else p.slug end,
                '[^a-zA-Z0-9]', '', 'g'), 8))
           || '-' || upper(left(regexp_replace(c.color, '[^a-zA-Z0-9]', '', 'g'), 6))
           || '-' || s.size,
       coalesce(o.qty, 8)
  from public.products p
  join public.brands b on b.id = p.brand_id
  join colorway c on c.product_slug = p.slug
  join run r on r.gender = p.gender
  cross join lateral unnest(r.sizes) as s(size)
  left join override o on o.product_slug = p.slug and o.size = s.size
on conflict (product_id, size, color) do update
  set sku = excluded.sku, color_hex = excluded.color_hex, stock_quantity = excluded.stock_quantity;

-- --- collections ----------------------------------------------------------
insert into public.collections (name, slug, description, sort_order) values
  ('New arrivals', 'new-arrivals', 'Just landed on the shelf.', 1),
  ('Monsoon ready', 'monsoon-ready', 'Waterproof, washable, and happy in standing water.', 2),
  ('Under ₹2,000', 'under-2000', 'Everything on this rail is under two thousand rupees.', 3)
on conflict (slug) do update set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;
insert into public.collection_products (collection_id, product_id, sort_order) values
  ((select id from public.collections where slug = 'new-arrivals'), (select id from public.products where slug = 'adidas-samba-og-mens'), 0),
  ((select id from public.collections where slug = 'new-arrivals'), (select id from public.products where slug = 'new-balance-550-mens'), 1),
  ((select id from public.collections where slug = 'new-arrivals'), (select id from public.products where slug = 'asics-gel-nimbus-27-mens'), 2),
  ((select id from public.collections where slug = 'new-arrivals'), (select id from public.products where slug = 'adidas-gazelle-womens'), 3),
  ((select id from public.collections where slug = 'new-arrivals'), (select id from public.products where slug = 'nike-air-max-90-mens'), 4),
  ((select id from public.collections where slug = 'new-arrivals'), (select id from public.products where slug = 'woodland-camel-boot-mens'), 5),
  ((select id from public.collections where slug = 'monsoon-ready'), (select id from public.products where slug = 'crocs-classic-clog-unisex'), 0),
  ((select id from public.collections where slug = 'monsoon-ready'), (select id from public.products where slug = 'adidas-adilette-slide-unisex'), 1),
  ((select id from public.collections where slug = 'monsoon-ready'), (select id from public.products where slug = 'bata-floater-sandal-mens'), 2),
  ((select id from public.collections where slug = 'monsoon-ready'), (select id from public.products where slug = 'crocs-brooklyn-slide-womens'), 3),
  ((select id from public.collections where slug = 'monsoon-ready'), (select id from public.products where slug = 'crocs-kids-clog'), 4),
  ((select id from public.collections where slug = 'monsoon-ready'), (select id from public.products where slug = 'puma-flip-flop-unisex'), 5),
  ((select id from public.collections where slug = 'under-2000'), (select id from public.products where slug = 'campus-north-plus-mens'), 0),
  ((select id from public.collections where slug = 'under-2000'), (select id from public.products where slug = 'bata-derby-mens'), 1),
  ((select id from public.collections where slug = 'under-2000'), (select id from public.products where slug = 'bata-floater-sandal-mens'), 2),
  ((select id from public.collections where slug = 'under-2000'), (select id from public.products where slug = 'bata-school-shoe-kids'), 3),
  ((select id from public.collections where slug = 'under-2000'), (select id from public.products where slug = 'campus-kids-sneaker'), 4),
  ((select id from public.collections where slug = 'under-2000'), (select id from public.products where slug = 'puma-flip-flop-unisex'), 5),
  ((select id from public.collections where slug = 'under-2000'), (select id from public.products where slug = 'bata-loafer-womens'), 6)
on conflict (collection_id, product_id) do update set sort_order = excluded.sort_order;

-- --- the homepage hero ----------------------------------------------------
-- Two crops of one scene. A 16:9 hero cropped to a 390px phone loses the
-- shoe; a phone-shaped hero stretched across a desktop loses the point.
-- placement is the natural key: one hero per placement, replaced on reseed.
delete from public.banners where placement = 'home_hero';
insert into public.banners (placement, image_url, mobile_image_url, headline, subtext, cta_label, cta_href, sort_order)
values ('home_hero', '/seed/hero-desktop.svg', '/seed/hero-mobile.svg', 'Every size we hold, shown on every shoe', 'Sneakers, formal shoes, boots and sandals for men, women and kids.', 'Shop all footwear', '/shop', 0);

-- --- CMS pages ------------------------------------------------------------
insert into public.pages (slug, title, body, meta_description, is_published) values
  ('about', 'About Foot Vault', 'Foot Vault is an independent footwear shop. We stock sneakers, formal shoes, boots, sports shoes and sandals for men, women and kids, from brands people actually ask for.

We hold every size we list. If a size shows as sold out on a product page, it is genuinely out of stock — we do not hide sizes to make a size run look fuller than it is.

Orders are packed and dispatched from our own shelves, not a drop-shipper''s. If something is wrong with what arrives, one message sorts it out.', 'An independent footwear shop stocking sneakers, formal shoes, boots and sandals for men, women and kids.', true),
  ('contact', 'Contact us', 'The fastest way to reach us is WhatsApp — we answer during shop hours and usually within the hour.

For an existing order, send your order number (it looks like FV-2026-00147) and we can pull it up straight away.

Our contact details and opening hours are in the footer of every page, and they are kept current from the shop''s own settings.', 'Phone, WhatsApp and email for Foot Vault, plus our shop address and opening hours.', true),
  ('shipping', 'Shipping', 'We ship across India from our store in Cuddapah, Andhra Pradesh.

Orders placed before 4pm on a working day are dispatched the same day. Most addresses receive in 3–5 working days; remote pin codes can take longer.

**Paying online** — delivery is free on orders of ₹2,499 or more. Below that you pay what the courier charges to reach your pin code. The exact figure appears as soon as you enter your pin code, never added at the last step.

**Pay on Delivery** — you pay the delivery charge online when you place the order, and the rest in cash to the courier when it arrives. Your order is not placed until that first payment goes through.

Delivery is charged on every Pay-on-Delivery order, whatever its value, and it is higher than the online rate. A parcel refused at the door costs us both the delivery and the return, so the charge covers the round trip. Paying in full online is always cheaper, and free above ₹2,499.

Checkout shows all three figures before you pay: what you pay now, what the courier will collect, and the total.

Not every courier will collect cash at every pin code. If yours is one they will not, the option is not offered and you can pay online instead — the order still comes to the same address. A very small number of pin codes have no courier service from us at all, and checkout will say so before you pay rather than take an order we cannot deliver.', 'Delivery times, what the courier charges, and how Pay on Delivery works at Foot Vault.', true),
  ('returns', 'Returns and damage', 'Please read this before you buy. Our policy is narrower than most online shops and we would rather you know that now than discover it later.

**We do not offer refunds.** Not on change of mind, not on size, not on colour. Once an order is placed it is yours.

**We do not take returns online.** There is no returns button in your account and no pickup will be arranged. Everything below happens by contacting the store directly.

**If a pair arrives damaged, we will replace it.** That is the one thing we cover, and it comes with a hard deadline:

- Contact us **within 24 hours of the parcel being delivered**. After that we cannot help, because we can no longer tell damage in transit from damage in use.
- Call or WhatsApp the store. Do not wait for an email reply.
- Keep the box, the packaging and the courier label. Send us photographs of the damage and of the packaging it arrived in — the courier will not accept a claim without them.
- Do not wear the pair. A sole that has been outside cannot be assessed or replaced.

If we agree the pair was damaged in transit, we send a replacement of the same item in the same size, subject to us holding it. If we do not hold it, we will agree something with you directly.

**Sizes.** We cannot exchange for a different size, so please use the size guide on every product page before ordering, and ask us if you are unsure.

**Pay on Delivery.** The delivery charge is paid online when you place the order, and it is not refundable — it pays the courier to carry the parcel to you, and again to carry it back if it is refused.

Nothing on this page affects your statutory rights under Indian consumer law.', 'Foot Vault replaces items damaged in shipment, reported within 24 hours of delivery. No refunds, no online returns.', true),
  ('size-guide', 'Size guide', 'Every size on this site is UK. The conversions below are the ones we use.

UK 6 = EU 40 = US 7. UK 7 = EU 41 = US 8. UK 8 = EU 42 = US 9. UK 9 = EU 43 = US 10. UK 10 = EU 44 = US 11. UK 11 = EU 45.5 = US 12. UK 12 = EU 47 = US 13.

To measure at home: stand on a sheet of paper with your heel against a wall, mark the tip of your longest toe, and measure the distance in centimetres. Do it in the evening, when your feet are at their largest, and measure both — most people have one foot slightly bigger and you should buy for that one.

Where a shoe runs small or large we say so on its product page.', 'UK, EU and US shoe size conversions, and how to measure your foot at home.', true),
  ('privacy', 'Privacy policy', 'We collect what an order needs and nothing else: your name, delivery address, phone number and email.

We use it to pack and deliver your order, to contact you about that order, and to show you your order history when you sign in. We do not sell it, and we do not share it with anyone other than the courier carrying your parcel.

Your bag is stored against a token in your browser until you sign in, at which point it moves to your account.

To have your account and its data deleted, contact us and we will remove it within 7 days. Orders already placed are kept as long as the law requires us to keep sales records.', 'What data Foot Vault collects, why, and how to have it removed.', true),
  ('terms', 'Terms of sale', 'Prices are in Indian rupees and include all taxes. The price you see in your bag is the price you pay.

An order is confirmed when we accept it, not when it is placed. If an item sells out between your order and our packing it, we will tell you which item and refund that line in full.

Stock counts on this site are live. Where a product page says only two are left in your size, that is the real number on our shelf.

Nothing here affects your statutory rights.', 'The terms that apply when you buy from Foot Vault.', true)
on conflict (slug) do update set title = excluded.title, body = excluded.body, meta_description = excluded.meta_description, is_published = excluded.is_published;

-- --- settings -------------------------------------------------------------
insert into public.site_settings (key, value, description) values
  ('store_name', '"Foot Vault"'::jsonb, 'Shop name, used in the header, metadata and invoices.'),
  ('store_tagline', '"Every step counts"'::jsonb, 'Wordmark tagline.'),
  ('announcement', '{"text":"Damage on arrival? Tell us within 24 hours · Free shipping over ₹2,499","href":"/page/returns","is_active":true}'::jsonb, 'The thin strip above the header.'),
  ('contact', '{"email":"hello@footvault.in","phone":"+91 80 4718 2200","whatsapp":"+91 98450 22001","address":"42 Commercial Street, Shivaji Nagar, Bengaluru 560001"}'::jsonb, 'Shown in the footer and on the contact page.'),
  ('business_hours', '{"weekday":"10:30 – 20:30","saturday":"10:30 – 21:00","sunday":"11:00 – 19:00"}'::jsonb, 'Opening hours, shown on the contact page.'),
  ('social', '{"instagram":"https://instagram.com/footvault","facebook":"https://facebook.com/footvault"}'::jsonb, 'Social links in the footer.'),
  ('shipping', '{"free_above_paise":249900,"currency":"INR","regions":["IN"],"cod_enabled":true,"cod_advance_mode":"greater_of","cod_advance_minimum_paise":9900,"cod_advance_fixed_paise":9900,"fallback_fee_paise":{"razorpay":19900,"cod":34900}}'::jsonb, 'Free-delivery threshold, the Pay-on-Delivery advance rule, and the amounts used only when Shiprocket cannot be reached. Rates themselves always come from the courier.'),
  ('return_window_days', '1'::jsonb, 'Days from delivery in which shipment damage can be reported. One day — the policy is 24 hours, replacement only, no refunds.'),
  ('payment_methods', '{"cod":true,"online":false}'::jsonb, 'Cash on delivery only for now; the online gateway sits behind the same interface.')
on conflict (key) do update set value = excluded.value, description = excluded.description;

-- --- homepage -------------------------------------------------------------
-- Replaced wholesale: sort_order is the identity of a section here, and a
-- reseed should restore the designed homepage rather than merge with
-- whatever the owner last dragged around.
delete from public.homepage_sections;
insert into public.homepage_sections (section_type, title, subtitle, payload, sort_order) values
  ('hero', 'Every size we hold, shown on every shoe', 'Sneakers, formal shoes, boots and sandals for men, women and kids.', '{"eyebrow":"Foot Vault","cta_label":"Shop all footwear","cta_href":"/shop","secondary_cta_label":"New arrivals","secondary_cta_href":"/collection/new-arrivals"}'::jsonb, 1),
  ('category_grid', 'Shop by department', NULL, '{"category_slugs":["men","women","kids"]}'::jsonb, 2),
  ('product_rail', 'New arrivals', 'Just landed on the shelf.', '{"collection_slug":"new-arrivals","cta_href":"/collection/new-arrivals"}'::jsonb, 3),
  ('promo_strip', 'What you can count on', NULL, '{"items":[{"label":"Damaged in transit? Replaced","detail":"Tell us within 24 hours of delivery."},{"label":"Free shipping over ₹2,499","detail":"The courier''s own rate below that."},{"label":"Pay on Delivery","detail":"Delivery charge now, the rest in cash at the door."},{"label":"Live stock counts","detail":"If it says two left, there are two."}]}'::jsonb, 4),
  ('product_rail', 'Monsoon ready', 'Waterproof, washable, and happy in standing water.', '{"collection_slug":"monsoon-ready","cta_href":"/collection/monsoon-ready"}'::jsonb, 5),
  ('banner', 'Under ₹2,000', 'School shoes, everyday trainers and sandals that do the job.', '{"cta_label":"Shop the rail","cta_href":"/collection/under-2000"}'::jsonb, 6);

