import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    /**
     * next/image only serves the qualities named here — Next 16 defaults the
     * allowlist to [75] and answers 400 for anything else. The hero asks for 82
     * (see home-sections.tsx), which meant the optimiser quietly clamped the
     * emitted srcset back to 75 while the code claimed otherwise, and a direct
     * request for q=82 returned 400. Naming it makes the number in the code the
     * number that ships.
     */
    qualities: [75, 82],
    /**
     * The seed catalog ships drawn SVG product assets (see
     * scripts/generate-seed-images.ts), and next/image refuses to serve SVG
     * without this flag because an SVG can carry script.
     *
     * Safe here for two reasons, and both have to stay true:
     *   1. Every SVG the optimiser sees is first-party — generated by that
     *      script into /public/seed, never uploaded.
     *   2. The CSP below is applied to optimised images, so even a hostile SVG
     *      is sandboxed with scripting off.
     *
     * Migration 0011 removed image/svg+xml from the product-images and
     * category-images buckets for the same reason: once the owner can upload,
     * "first-party only" would stop being true for that path.
     */
    dangerouslyAllowSVG: true,
    contentDispositionType: "attachment",
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
    remotePatterns: [
      {
        // Real photography, once the owner uploads it from /admin/products.
        protocol: "https",
        hostname: "*.supabase.co",
        pathname: "/storage/v1/object/public/**",
      },
    ],
  },
};

export default nextConfig;
